version: "3.9"
services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: rolonbot-lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx512m
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml:ro
    ports:
      - "2333:2333"

  bot:
    build: .
    container_name: rolonbot
    restart: unless-stopped
    depends_on: [lavalink]
    env_file: .env
    environment:
      - LAVALINK_HOST=lavalink
    ports:
      - "8787:8787"
